package io.github.enelrith.bluebay.users.dto;

import java.time.LocalDateTime;

/**
 * DTO used in {@link io.github.enelrith.bluebay.users.controllers.UserController} for the user registration response
 * @param id User id that is automatically generated for each user by the database
 * @param email User email
 * @param password Hashed user password
 * @param createdAt Timestamp from when the user registered. Automatically generated by the database once.
 * @param updatedAt Timestamp from when the user last updated any user details. Automatically generated by the database each time.
 * @param verifiedAt Timestamp from when the user verified their account. Null after registration process. Automatically generated by the database once.
 */
public record RegisterUserResponse(long id, String email, String password, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime verifiedAt) {
}
